openapi: 3.0.2
info:
  version: '1.0'
  title: OpenAPI Course
  description: 'Spec for course'
  contact:
    name: MDC Bowen
    url: https://www.mdcbowen.info
    email: mbowen@mdcbowen.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://development.gigantic-server.com/v1
    description: Development server
  - url: https://prod.gigantic-server.com/v1
    description: Production server
paths:
  /v1/customers:
    get:
      summary: Returns a list of customers.
      description: Optional extended description in Markdown.
      operationId: getCustomers
      responses:
        '200':
          description: A JSON array of customer names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string


