openapi: 3.0.2
info:
  title: OpenAPI Course
  description: Spec for course
  contact:
    name: MDC Bowen
    url: https://www.mdcbowen.info
    email: mbowen@mdcbowen.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
- url: https://development.gigantic-server.com/v1
  description: Development server
paths:
  /v1/beers:
    get:
      summary: Returns a list of beers.
      description: Optional extended description in Markdown.
      operationId: getBeers
      responses:
        "200":
          description: A JSON array of beers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "404":
          description: File Not Found
          content:
            application/json:
              schema:
                title: File Not Found
  /v1/customers:
    get:
      summary: Returns a list of customers.
      description: Optional extended description in Markdown.
      operationId: getCustomers
      responses:
        "200":
          description: A JSON array of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components: {}
